### ISSUE TITLE
how to read the  .flo files and convert .jpg to .ppm

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [liruoteng/FlowNet#1]
Thanks for your share!
I make your code successfully and get the flownets-pred-NNNNNNN.flo such as flownets-pred-0000004.flo. 
But i can not read it like a image .
 Moreover,The input of the code is .ppm files .
Could you please tell me how to convert the common images(.jpg) to .ppm files .
    My goal is get the result showed in the paper 's demo(https://www.youtube.com/watch?=k_wkDLJ8lJE). 
Would you like to tell me how to get the wonderful result(input video and then output optical flow video).

**Comment by liruoteng** [comment]
Thank you for your comment.

If you are familiar with Python, you may want to use PIL (Pillow) as below

```
from PIL import Image
img = Image.open('your_filename.ppm')
img.save('output_filename.jpg')
```

**Comment by 3DMM-ICME2023** [comment]
Thanks for your reply!
I can convert the .ppm to  .jpg according to your guidance. But the output of the FlowNet is .flo files. Could you please tell me how to convert .flo to .jpg so that i can get the same result as the paper's demo?

**Comment by liruoteng** [comment]
HI Liu,

Please look at another repository of mine if you are interested:
https://github.com/liruoteng/OpticalFlowToolkit

Thanks
