### ISSUE TITLE
How to download flownet_official.caffemodel

### ISSUE THREAD

**Issue by vra** [liruoteng/FlowNet#13]
Hi @liruoteng ,
When I run ` ./demo_flownet.py S data/0000000-img0.ppm data/0000000-img1.ppm`, I got a error in logfile:
```bash
F0408 23:38:34.559917 14274 io.cpp:54] Check failed: fd != -1 (-1 vs. -1) File not found: ./model_simple/flownet_official.caffemodel
*** Check failure stack trace: ***
    @     0x7f0a5187adaa  (unknown)
    @     0x7f0a5187ace4  (unknown)
    @     0x7f0a5187a6e6  (unknown)
    @     0x7f0a5187d687  (unknown)
    @     0x7f0a52015604  caffe::ReadProtoFromBinaryFile()
    @     0x7f0a5201cfac  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f0a51fd880a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f0a51fd8891  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40938b  test()
    @           0x407fa8  main
    @     0x7f0a50b88f45  (unknown)
    @           0x4084ec  (unknown)
    @              (nil)  (unknown)
``` 
It seems that the `flownet_official.caffemodel` is not found. I checked the README file of this repo but not found how to download this file. So cloud you give me some advice to get this file?  Great thanks!
Also I can help to improve this repo to make it easier to use, like update README, update to current caffe, add lastest CUDA support. what do you think?

**Comment by liruoteng** [comment]
Hi vra, thanks for your comment. 

Regarding the flownet_official.caffemodel, you may download it from https://lmb.informatik.uni-freiburg.de/resources/software.php

And thanks for your suggestions. I will update the link in the readme for better usability. 

Yes, please feel free to improve it with better user friendly information!

For your last PR, please let me test it on my own environment before I merge them with. 

Thanks
Best
Ruoteng
