### ISSUE TITLE
What is the difference between your repo with the offical FlowNet code?

### ISSUE THREAD

**Issue by xmfbit** [liruoteng/FlowNet#15]
Hi, thank you for your work. But I wonder what the difference is between your repo and the offical FlowNet implemented by Caffe offered in the website of University of Freiburg: https://lmb.informatik.uni-freiburg.de/resources/software.php ?
Thanks!

**Comment by liruoteng** [comment]
Hi this flownet is the early version without any data augmentation on the fly. I made modification specially for my own project, but I did not push it in the repo cuz it will be quite confusing. Please cite their work if you happen to use this repo as well. Thanks.

**Comment by xmfbit** [comment]
Thank you.
