### ISSUE TITLE
How to get weights from the simple model?

### ISSUE THREAD

**Issue by wuaming** [liruoteng/FlowNet#17]
Dear Professor:
         I compile flownet successfully and download the simple model from your link. But when I try to get the weights from your model, there is an error.
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 51:12: Expected integer.
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0703 14:50:35.258781 15877 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/wam2/FlowNet-master/models/flownet/model_simple/deploy.tpl.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
Could you give me some help?

**Comment by liruoteng** [comment]
Please check your deploy.tpl.prototxt file, line 52, column 12.

Thanks

**Comment by wuaming** [comment]
Thank you very much! The problem has been solved. But there is another problem.
I0704 23:23:08.718444  5949 layer_factory.hpp:76] Creating layer Image1
I0704 23:23:08.718478  5949 net.cpp:108] Creating Layer Image1
I0704 23:23:08.718488  5949 net.cpp:417] Image1 -> img0
I0704 23:23:08.718508  5949 image_data_layer.cpp:36] Opening file tmp/img1.txt
I0704 23:23:08.718523  5949 image_data_layer.cpp:50] A total of 0 images.
Segmentation fault (core dumped)

**Comment by wuaming** [comment]
This is the content of img1.txt.
data/0000000-img0.ppm

**Comment by wuaming** [comment]
Thanks. The above problem has been solved.
