### ISSUE TITLE
Loss Question

### ISSUE THREAD

**Issue by wuaming** [liruoteng/FlowNet#18]
When you compute the epe loss, do you normalize the optical flow?

**Comment by liruoteng** [comment]
no, the epe loss is just L2 norm.

**Comment by wuaming** [comment]
How long do you take to train the model?

**Comment by liruoteng** [comment]
If you train it on GTX 1080 level GPU card, it will probably take you at
least 3 days to fully complete.

**Comment by wuaming** [comment]
The size of input image is not equal the output size of flow. But how do you process the groundtruth? And how do you resize the flow to your output size?

**Comment by wuaming** [comment]
When you train the model, dose the dropout affect the accuracy of the model?

**Comment by liruoteng** [comment]
Hi, for the image size problem, you may want to see the resample layer in the train.prototxt, or deploy.prototxt. 
And there is no dropout in this model. 

thanks.

**Comment by wuaming** [comment]
![flow](https://user-images.githubusercontent.com/26898749/28156278-a9fc00e2-67e4-11e7-824e-c6626d222255.png) When I finish the train, the result is not smooth.

**Comment by wuaming** [comment]
When you visualize the flow, do you use the smooth operation?

**Comment by wuaming** [comment]
Dear Professor, where is the code about data augmentation?

**Comment by liruoteng** [comment]
Hi, regarding visualization, we don't use smooth operation. 
For data augmentation, please refer to the FlowNet paper. 

Thanks
RT

**Comment by JasonZhangFan** [comment]
I'm wondering if we want to use it for real application, how can we get ground truth of the input as training material?

**Comment by liruoteng** [comment]
Hi, the ground truth is always difficult to collect and calculate for real data. You may follow this paper to see how they generate [KITTI dataset](http://www.cvlibs.net/publications/Geiger2012CVPR.pdf)
