### ISSUE TITLE
error during the make

### ISSUE THREAD

**Issue by bragilee** [liruoteng/FlowNet#2]
I am using the flownet code and trying to compile and build it bu I have got some errors as followings, is there anyone encountering the similar issues?

In advance, thank you so much for your time and help.

argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/home/runze/flownet-release/include/caffe/util/cudnn.hpp(123): error: too few arguments in function call

2 errors detected in the compilation of "/tmp/tmpxft_00002859_00000000-5_batch_reindex_layer.cpp4.ii".
CMake Error at cuda_compile_generated_batch_reindex_layer.cu.o.Release.cmake:267 (message):
  Error generating file
  /home/runze/flownet-release/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_batch_reindex_layer.cu.o

make[2]: **\* [src/caffe/CMakeFiles/caffe.dir/build.make:86: src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_batch_reindex_layer.cu.o] Error 1
make[2]: **\* Waiting for unfinished jobs....

**Comment by liruoteng** [comment]
Hi, @bragilee  if you have no more issue regarding compilation of this framework. I will close this issue then.

**Comment by bragilee** [comment]
Hi, @liruoteng Sorry for late reply as I was in travelling. Thank you so much for your help.
