### ISSUE TITLE
notiong make for 'tools'

### ISSUE THREAD

**Issue by whrljt** [liruoteng/FlowNet#20]
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
make: Nothing to be done for 'tools'.
------------------------------------------------------------------------------------------------------------------------------------  I run 'make -j 5 all tools',  everything is ok, but it show  'make: Nothing to be done for 'tools'.' at last.

**Comment by whrljt** [comment]
basepath:  /home/whr/FlowNet/models/flownet
bin:  ../../.build_release/tools/caffe ../../.build_release/tools/get_image_size
Image files: ['data/0000000-img0.ppm', 'data/0000000-img1.ppm']
Image sizes: [[512, 384], [512, 384]]
Executing ../../.build_release/tools/caffe test -model tmp/deploy.prototxt -weights ./model_simple/flownet_official.caffemodel -iterations 1 -gpu 1

The resulting FLOW is stored in flownets-pred-NNNNNNN.flo
----------------------------------------------------------------------------------------------------------------------------------Then I run './demo_flownet.py S data/0000000-img0.ppm data/0000000-img1.ppm', the result is this. What's wrong? My computer is ubuntu 16.04 with cuda 8.0 and cudnn 5.1.

**Comment by liruoteng** [comment]
Hi , Nothing to be done for 'tools' basically means that you've already compiled the target 'tools' and no dependence has been changed since your last compilation. 

2. there is nothing wrong with your code, the flow file has been generated successfully. 

I'll closed this issue. 

thanks

**Comment by whrljt** [comment]
Sorry, I forgot to say there was no flow file generated, it generated nothing.
