### ISSUE TITLE
Caffe tool binaries not found. Did you compile caffe with tools (make all tools)?

### ISSUE THREAD

**Issue by zhengzhugithub** [liruoteng/FlowNet#21]
I follw the caffe instruction and run "make all tools ", it shows ''make: Nothing to be done for `tools'.'' but when I go into next step, it shows ''Caffe tool binaries not found. Did you compile caffe with tools (make all tools)?''

**Comment by liruoteng** [comment]
Hi, have you compiled the caffe framework?  could you also check whether your root directory is pointing to the correct caffe binary file?

thanks

**Comment by zhengzhugithub** [comment]
I solve the problem，thank you

发自我的 iPhone
