### ISSUE TITLE
Error in test_flownet.py

### ISSUE THREAD

**Issue by Mehuli-Ruh11** [liruoteng/FlowNet#22]
Hi,
While testing the trained model, for ChairSDHom dataset, I am getting the following error in logfile:
I0717 16:38:01.021663 21905 layer_factory.hpp:76] Creating layer Image1
I0717 16:38:01.021692 21905 net.cpp:108] Creating Layer Image1
I0717 16:38:01.021698 21905 net.cpp:417] Image1 -> img0
I0717 16:38:01.021718 21905 image_data_layer.cpp:36] Opening file tmp/img1.txt
I0717 16:38:01.022765 21905 image_data_layer.cpp:50] A total of 5927 images.
E0717 16:38:01.022781 21905 io.cpp:80] Could not open or find file ‰PNG
F0717 16:38:01.022891 21905 image_data_layer.cpp:64] Check failed: cv_img.data Could not load ‰PNG
*** Check failure stack trace: ***
    @     0x7f2c60dfb5cd  google::LogMessage::Fail()
    @     0x7f2c60dfd433  google::LogMessage::SendToLog()
    @     0x7f2c60dfb15b  google::LogMessage::Flush()
    @     0x7f2c60dfde1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2c615a3f6a  caffe::ImageDataLayer<>::DataLayerSetUp()
    @     0x7f2c615110d3  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f2c61467c8e  caffe::Net<>::Init()
    @     0x7f2c61469d53  caffe::Net<>::Net()
    @           0x408a87  test()
    @           0x407238  main
    @     0x7f2c60089830  __libc_start_main
    @           0x4078f9  _start
    @              (nil)  (unknown)

Can anyone please help me with this?

**Comment by liruoteng** [comment]
Hi, I guess it has something to do with your input png files. You may take a look imagedata.cpp file to debug it a bit. 

thanks

**Comment by Mehuli-Ruh11** [comment]
Maybe I am  missing something. Just to confirm, to test the trained model,  we only need to run test_flownet.py. Is that right?

**Comment by liruoteng** [comment]
You may run demo_flownet.py provided by the author to process any two input frames (refer to flownet readme to know how to run demo). 
test_flownet.py  script is written by me for my own specific testing. If you want to use it, you probably need to correctly specify your img1_list_test.txt, img2_list_test.txt and flo_list_test.txt files. 

thanks
RT
