### ISSUE TITLE
error in demo_flownet.py

### ISSUE THREAD

**Issue by whrljt** [liruoteng/FlowNet#24]
After compile caffe, I want to try out FlowNetS on a sample image pair, but some error happened, the errors are recorded in the logfile as follow:
----------------------------------------------------------------------------------------------------------------------------------
I0726 08:44:48.698459  8804 net.cpp:745] Ignoring source layer flow_loss6
I0726 08:44:48.702649  8804 net.cpp:745] Ignoring source layer predict_flow5_Convolution2_0_split
I0726 08:44:48.702663  8804 net.cpp:745] Ignoring source layer Downsample2
I0726 08:44:48.702669  8804 net.cpp:745] Ignoring source layer flow_loss5
I0726 08:44:48.704697  8804 net.cpp:745] Ignoring source layer predict_flow4_Convolution3_0_split
I0726 08:44:48.704710  8804 net.cpp:745] Ignoring source layer Downsample3
I0726 08:44:48.704715  8804 net.cpp:745] Ignoring source layer flow_loss4
I0726 08:44:48.705476  8804 net.cpp:745] Ignoring source layer predict_flow3_Convolution4_0_split
I0726 08:44:48.705487  8804 net.cpp:745] Ignoring source layer Downsample4
I0726 08:44:48.705493  8804 net.cpp:745] Ignoring source layer flow_loss3
I0726 08:44:48.705688  8804 net.cpp:745] Ignoring source layer predict_flow2_Convolution5_0_split
I0726 08:44:48.705698  8804 net.cpp:745] Ignoring source layer Downsample5
I0726 08:44:48.705703  8804 net.cpp:745] Ignoring source layer flow_loss2
I0726 08:44:48.705710  8804 net.cpp:745] Ignoring source layer Silence1
I0726 08:44:48.705716  8804 net.cpp:745] Ignoring source layer Silence2
I0726 08:44:48.705723  8804 net.cpp:745] Ignoring source layer Silence3
I0726 08:44:48.705729  8804 net.cpp:745] Ignoring source layer Silence4
I0726 08:44:48.706749  8804 caffe.cpp:290] Running for 1 iterations.
*** Aborted at 1501029888 (unix time) try "date -d @1501029888" if you are using GNU date ***
PC: @     0x7fe745709773 caffe::FLOWriterLayer<>::Forward_cpu()
*** SIGSEGV (@0x3a0) received by PID 8804 (TID 0x7fe7466a0740) from PID 928; stack trace: ***
    @     0x7fe7438504b0 (unknown)
    @     0x7fe745709773 caffe::FLOWriterLayer<>::Forward_cpu()
    @     0x7fe7458aa14a caffe::Net<>::ForwardFromTo()
    @     0x7fe7458aa4d7 caffe::Net<>::Forward()
    @           0x4096ff test()
    @           0x4075a8 main
    @     0x7fe74383b830 __libc_start_main
    @           0x407e79 _start
    @                0x0 (unknown)
------------------------------------------------------------------------------------------------------------------------------
What should I do to run it successfully?

**Comment by liruoteng** [comment]
sorry, I can hardly debug the error by the information you provided. 

Will you please check if you have all the necessary files, models, weights, at the desired location. 

thanks
RT

**Comment by super-wcg** [comment]
@whrljt did you solve the problem?
