### ISSUE TITLE
prediction is flipped version of ground truth

### ISSUE THREAD

**Issue by Mehuli-Ruh11** [liruoteng/FlowNet#25]
While visualizing the results, got by test_flownet.py on ChairSDHom dataset, the prediction is flipped 180 degree. 
Ground truth:
![figure_5](https://user-images.githubusercontent.com/27453659/28584842-052b6ede-7123-11e7-9d77-3f2159f04622.png)
Prediction:
![figure_1-5](https://user-images.githubusercontent.com/27453659/28584847-06e04164-7123-11e7-8485-aafda03211a6.png)
Does anyone have idea about what could be the reason for this ?

**Comment by liruoteng** [comment]
I think it is because you use data layer to read the image and the layer has function to mirror the input image. 

thanks
RT

**Comment by Mehuli-Ruh11** [comment]
Yes ! That was the problem while reading the .flo file. Thanks !!
