### ISSUE TITLE
training on kitti 

### ISSUE THREAD

**Issue by Timo-hab** [liruoteng/FlowNet#3]
Hi,
I want to train FlowNet_Simple on Kitti, but that lead to that error:
```
F1101 15:37:24.878199  7913 concat_layer.cpp:42] Check failed: top_shape[j] == 
bottom[i]->shape(j) (39 vs. 40) All inputs must have the same shape, except at concat_axis.
```
I played something with the padding, so I could start the training, but after 0 iterations it gave me the following error:
```
F1101 15:34:05.412156  7855 data_transformer.cpp:240] Check failed: height <= img_height (375 vs. 370) 
*** Check failure stack trace: ***
```
And I have no idea how to solve that.
The input resolution of Kitti is 375x1242px. Have you still the train.protoxt for kitti or do you have an idea how to set the padding correctly? Thank you in advance!

**Comment by liruoteng** [comment]
Hi, I did not train KITTI successfully because of the size issue. 
It is possible to train the KITTI image if try to change the KITTI image size to the multiples of 64. But you need to be very carefully about the learning rate.
