### ISSUE TITLE
flownet_official.caffemodel no found

### ISSUE THREAD

**Issue by AgatheMead** [liruoteng/FlowNet#5]
Hi,

I am new to caffe and I am interested in learning FlowNet, when I tried to run demo_flownet.py, it was really confused to see this:

F1223 14:49:15.715883 31183 io.cpp:54] Check failed: fd != -1 (-1 vs. -1) File not found: ./model_simple/flownet_official.caffemodel
*** Check failure stack trace: ***
    @     0x7fec7c42cdaa  (unknown)
    @     0x7fec7c42cce4  (unknown)
    @     0x7fec7c42c6e6  (unknown)
    @     0x7fec7c42f687  (unknown)
    @     0x7fec7ca597c4  caffe::ReadProtoFromBinaryFile()
    @     0x7fec7ca81766  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fec7cbb4a67  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fec7cbb4ad6  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x4074b7  test()
    @           0x405df0  main
    @     0x7fec7af7af45  (unknown)
    @           0x406513  (unknown)
    @              (nil)  (unknown)

The resulting FLOW is stored in flownets-pred-NNNNNNN.flo

Any suggestions? Many thanks!

**Comment by liruoteng** [comment]
Hi ,  as the caffemodel file is too big , I didn't upload it here. You may want to go to Freiburg cv website to download it. Thanks!

**Comment by AgatheMead** [comment]
@liruoteng Thanks!
